server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: pay
          uri: http://localhost:8081
          predicates:
            - Path=/payments/** 
        - id: room
          uri: http://localhost:8082
          predicates:
            - Path=/rooms/** 
        - id: mypage
          uri: http://localhost:8083
          predicates:
            - Path= /myPages/**
        - id: booking
          uri: http://localhost:8084
          predicates:
            - Path=/bookings/** 
        - id: notification
          uri: http://localhost:8085
          predicates:
            - Path=/notifications/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: pay
          uri: http://pay:8080
          predicates:
            - Path=/payments/** 
        - id: room
          uri: http://room:8080
          predicates:
            - Path=/rooms/** 
        - id: mypage
          uri: http://mypage:8080
          predicates:
            - Path= /myPages/**
        - id: booking
          uri: http://booking:8080
          predicates:
            - Path=/bookings/** 
        - id: notification
          uri: http://notification:8080
          predicates:
            - Path=/notifications/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080