apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: booking
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: booking
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 3